//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHeadLib.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHeadLib.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ; @generated
        ///; AHeadLib.Net
        ///; https://github.com/SakuraKoi/AHeadLib.Net
        ///; Powered by bodong | Modified by.SakuraKooi
        ///
        ///.DATA
        ///    ${EXTERNDEF_POINTERS}
        ///
        ///.CODE
        ///
        ///${FUNCTIONS}
        ///
        ///END
        /// 的本地化字符串。
        /// </summary>
        internal static string Asm_x64 {
            get {
                return ResourceManager.GetString("Asm_x64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; @generated
        ///; AHeadLib.Net
        ///; https://github.com/SakuraKoi/AHeadLib.Net
        ///; Powered by bodong | Modified by.SakuraKooi
        ///
        ///.MODEL FLAT
        ///
        ///.DATA
        ///    ${EXTERNDEF_POINTERS}
        ///
        ///.CODE
        ///
        ///${FUNCTIONS}
        ///
        ///END
        /// 的本地化字符串。
        /// </summary>
        internal static string Asm_x86 {
            get {
                return ResourceManager.GetString("Asm_x86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // generated by tools
        ///// AHeadLib.Net
        ///// https://github.com/bodong1987/AHeadLib.Net
        ///// Powered by bodong
        ///
        ///#include &lt;windows.h&gt;
        ///#include &quot;MiniTools.h&quot;
        ///
        ///#if defined(_WIN64) || defined(_X64) || defined(WIN64) || defined( __LP64__ )
        ///#define AHEAD_LIB_DOT_NET_X64_BUILD 1
        ///#else
        ///#define AHEAD_LIB_DOT_NET_X64_BUILD 0
        ///#endif
        ///
        ///// checked get function in native dll
        ///namespace
        ///{
        ///    LPVOID CheckedGetFunction(HMODULE module, const char* methodName)
        ///    {
        ///        const auto Result = reinterpret_cast&lt;LPV [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CppHelper {
            get {
                return ResourceManager.GetString("CppHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // generated by tools
        ///// AHeadLib.Net
        ///// https://github.com/bodong1987/AHeadLib.Net
        ///// Powered by bodong
        ///
        ///#include &lt;windows.h&gt;
        ///
        ///extern void CheckedLoad();
        ///extern void ExecuteUserCustomCodes();
        ///extern bool ShouldExecuteAttachCode();
        ///
        ///BOOL WINAPI DllMain(
        ///    HINSTANCE /*hInstance*/,  // handle to DLL module
        ///    DWORD fdwReason,     // reason for calling function
        ///    LPVOID lpvReserved)  // reserved
        ///{
        ///    // Perform actions based on the reason for calling.
        ///    switch (fdwReason)
        ///    {
        ///    c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DllMain {
            get {
                return ResourceManager.GetString("DllMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] solution {
            get {
                object obj = ResourceManager.GetObject("solution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 // @generated
        ///// AHeadLib.Net
        ///// https://github.com/SakuraKoi/AHeadLib.Net
        ///// Powered by bodong | Modified by.SakuraKooi
        ///
        ///#include &lt;Windows.h&gt;
        ///#include &lt;cassert&gt;
        ///#include &lt;tchar.h&gt;
        ///
        ///#define STRINGIFY(x) #x
        ///#define TO_STRING(x) STRINGIFY(x)
        ///
        ///#define MESSAGE_RAISE_LOCATION __FILE__ &quot;(&quot; TO_STRING(__LINE__) &quot;): &quot;
        ///
        ///// fill original library path here
        ///// use absolute file path
        ///void GetOriginalLibraryPath(TCHAR* bufferPtr, int bufferLength, const TCHAR* libName)
        ///{
        ///    assert(bufferPtr != nullptr); [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string UserImplementations {
            get {
                return ResourceManager.GetString("UserImplementations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] vcxprojTemplate {
            get {
                object obj = ResourceManager.GetObject("vcxprojTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] vcxprojTemplate_filters {
            get {
                object obj = ResourceManager.GetObject("vcxprojTemplate_filters", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
