// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include <windows.h>

extern void CheckedLoad();
extern void ExecuteUserCustomCodes();
extern bool ShouldExecuteAttachCode();

BOOL WINAPI DllMain(
    HINSTANCE hInstance, // handle to DLL module
    DWORD fdwReason, // reason for calling function
    LPVOID lpvReserved) // reserved
{
    // Perform actions based on the reason for calling.
    if (fdwReason == DLL_PROCESS_ATTACH) {
        // Initialize once for each new process.
        // Return FALSE to fail DLL load.
        DisableThreadLibraryCalls(hInstance);
        CheckedLoad();

        if (ShouldExecuteAttachCode()) {
            // apply user custom codes
            ExecuteUserCustomCodes();
        }
    }
    return TRUE; // Successful DLL_PROCESS_ATTACH.
}
